### ISSUE TITLE
Add volume calculator

### ISSUE THREAD

**Issue by davejane25** [davejane25/Calculators#16]
calculates volume of sphere, cuboid, pyramid

**Comment by DevanshUpadhyay26** [comment]
Hey assign me!

**Comment by dhruvdabhi101** [comment]
I would like to contribute

**Comment by davejane25** [comment]
sure do it @dhruvdabhi101

**Comment by ashish5433** [comment]
hii @davejane25 can you please assign this to me

**Comment by davejane25** [comment]
> hii @davejane25 can you please assign this to me

do it @ashish5433

**Comment by davejane25** [comment]
task done with #24
