### ISSUE TITLE
Add Quadratic equation calculator

### ISSUE THREAD

**Issue by davejane25** [davejane25/Calculators#18]
use  _**Ax^2 + Bx + C = 0**_  format

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
Hey! @davejane25  I want to work on this , can it be assign to me?🙂

**Comment by davejane25** [comment]
sure @SOUMOJIT-CHAKRABORTY do it!

**Comment by Ved142** [comment]
Hey @davejane25 , I would like to work on it . Please assign it to me.

**Comment by davejane25** [comment]
completed with #19
