### ISSUE TITLE
add area calculator 

### ISSUE THREAD

**Issue by davejane25** [davejane25/Calculators#2]
for circle, triangle, quadrilaterals

**Comment by void-57** [comment]
hey  @davejane25  please assign me

**Comment by davejane25** [comment]
@void-57 create folder named Area-calculator and then create simple website for it only using html/css/javascript.

**Comment by ashish5433** [comment]
hii @davejane25  please assign this to me

**Comment by davejane25** [comment]
> hii @davejane25  please assign this to me

Okay @ashish5433 do it

**Comment by davejane25** [comment]
Work done with #23
