### ISSUE TITLE
improve the ui of bmi calculator

### ISSUE THREAD

**Issue by Akshun-01** [davejane25/Calculators#22]
![image](https://user-images.githubusercontent.com/93793691/196808468-6d39b7d7-06f3-417a-a59d-adab912868a4.png)

The BMI Calculator is working fine, but the UI is not eye-pleasing in the least. If you think this is an issue which needs to be resolved please assign it to me

**Comment by davejane25** [comment]
> ![image](https://user-images.githubusercontent.com/93793691/196808468-6d39b7d7-06f3-417a-a59d-adab912868a4.png)
> 
> The BMI Calculator is working fine, but the UI is not eye-pleasing in the least. If you think this is an issue which needs to be resolved please assign it to me 

Ok @Akshun-01 make changes 👍

**Comment by davejane25** [comment]
Resolved problem
