### ISSUE TITLE
Add Calculators

### ISSUE THREAD

**Issue by davejane25** [davejane25/Calculators#27]
Add different types of useful calculators

**Comment by singhkaran202** [comment]
Hello@davejane25, Thanks for assigning me previous issue!!
 I'd like to work on this too...
Please assign me this also🙏

**Comment by davejane25** [comment]
> Hello@davejane25, Thanks for assigning me previous issue!!
>  I'd like to work on this too...
> Please assign me this also🙏
> 

Sure do it @singhkaran202

**Comment by adityabisoyi** [comment]
I have built a simple calculator. Can you assign this to me?

![image](https://user-images.githubusercontent.com/109476995/197257847-ccad64e0-a06d-4fbb-82e6-84f85a5bddb2.png)

**Comment by singhkaran202** [comment]
@adityabisoyi bro, I guess this simple calculator already exists in the repo

**Comment by singhkaran202** [comment]
@davejane25, I am working on this issue, I can add a calculator.....
Please reopen this issue 🙏
