### ISSUE TITLE
UI/UX improvement 

### ISSUE THREAD

**Issue by davejane25** [davejane25/Calculators#28]
Need to improve the UI of calculators, with responsiveness. Also make all  calculators in particular colour theme.

**Comment by shrutilenka** [comment]
Hey @davejane25  I am interested to solve this issue.Could you pls assign this to me?

**Comment by davejane25** [comment]
> Hey @davejane25  I am interested to solve this issue.Could you pls assign this to me?

Ok, do it @shrutilenka

**Comment by singhkaran202** [comment]
Hello @davejane25, I'd love to work on this if that's OK.
Could you please assign me this?

**Comment by davejane25** [comment]
So there are two people assigned for this.. whoever's would be best will be merged!!

**Comment by davejane25** [comment]
done with #30
