### ISSUE TITLE
CaeserCipher Calculator not working

### ISSUE THREAD

**Issue by davejane25** [davejane25/Calculators#31]
resolve the problem, and make it working
![image](https://user-images.githubusercontent.com/108894933/197366762-a44728d0-8f0a-466a-9eae-9b1d44787312.png)

**Comment by annakimdev** [comment]
Hi @davejane25! Please assign to me. I'd like to try it.

**Comment by davejane25** [comment]
done with #32

**Comment by Arunkumar-60** [comment]
@davejane25 , I don't see any issue there its working fine.

<img width="1440" alt="Screenshot 2022-10-23 at 1 06 13 PM" src="https://user-images.githubusercontent.com/84034637/197380266-7533b446-37c3-4302-9be8-13f812461e66.png">

**Comment by davejane25** [comment]
issue is already closed
