### ISSUE TITLE
Add favicon ico.

### ISSUE THREAD

**Issue by ishashankpatel** [davejane25/Calculators#4]
please assign me this for the hacktoberfest PR.
![image](https://user-images.githubusercontent.com/87827112/195932525-b27b4eaf-8a85-44ef-8a57-38289674d0cf.png)

**Comment by davejane25** [comment]
@Shashankfeeling also add calculator image in page background with 0.2 opacity

**Comment by ishashankpatel** [comment]
I added Favicon ico. Check the PR if its correct then please merge it. and please assign me this with hacktoberfest tags

**Comment by davejane25** [comment]
#7 done
